### ISSUE TITLE
[Suggestion] Add an option to play against a CPU.

### ISSUE THREAD

**Issue by ahinojos0029** [bossbadi-web/SHUFFL#1]

**Comment by bossbadi** [comment]
Good suggestion, will be considered

**Comment by aurvyn** [comment]
Hi, lead developer here. This is a very good suggestion and is something that should be implemented in a game like this anyway. There is a plan to include this once a menu feature is implemented, with an array of difficulty to choose from. This thread will be closed after the update is fulfilled.

**Comment by aurvyn** [comment]
There is now an ability to play against a CPU, with varying difficulties to choose from.
